import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Fuse from "fuse.js";

import { signIn, signOut, useSession } from "next-auth/react";
import { useState } from "react";

const marriageCandidates = [
  {
    name: "Alex",
    image: "https://stardewvalleywiki.com/mediawiki/images/0/04/Alex.png",
  },
  {
    name: "Elliott",
    image: "https://stardewvalleywiki.com/mediawiki/images/b/bd/Elliott.png",
  },
  {
    name: "Harvey",
    image: "https://stardewvalleywiki.com/mediawiki/images/9/95/Harvey.png",
  },
  {
    name: "Sam",
    image: "https://stardewvalleywiki.com/mediawiki/images/9/94/Sam.png",
  },

  {
    name: "Sebastian",
    image: "https://stardewvalleywiki.com/mediawiki/images/a/a8/Sebastian.png",
  },
  {
    name: "Shane",
    image: "https://stardewvalleywiki.com/mediawiki/images/8/8b/Shane.png",
  },
  {
    name: "Abigail",
    image: "https://stardewvalleywiki.com/mediawiki/images/8/88/Abigail.png",
  },
  {
    name: "Emily",
    image: "https://stardewvalleywiki.com/mediawiki/images/2/28/Emily.png",
  },
  {
    name: "Haley",
    image: "https://stardewvalleywiki.com/mediawiki/images/1/1b/Haley.png",
  },
  {
    name: "Leah",
    image: "https://stardewvalleywiki.com/mediawiki/images/e/e6/Leah.png",
  },
  {
    name: "Maru",
    image: "https://stardewvalleywiki.com/mediawiki/images/f/f8/Maru.png",
  },
  {
    name: "Penny",
    image: "https://stardewvalleywiki.com/mediawiki/images/a/ab/Penny.png",
  },
];
const AuthShowcase: React.FC = () => {
  const { data: secretMessage, isLoading } = trpc.useQuery([
    "auth.getSecretMessage",
  ]);

  const { data: sessionData } = useSession();

  return (
    <div>
      {sessionData && <p>Logged in as {sessionData?.user?.name}</p>}
      {secretMessage && <p>{secretMessage}</p>}
      <button
        className="px-4 py-2 border-2 border-blue-500 rounded-md"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  const [search, setSearch] = useState("");
  const options = {
    includeScore: true,
    // Search in `author` and in `tags` array
    keys: ["name"],
  };

  const fuse = new Fuse(marriageCandidates, options);

  const result = fuse.search(search);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-start items-center p-4 overflow-y-scroll">
        <h1 className="text-6xl font-bold">The Stardew Times</h1>
        <div className="w-full md:w-3/4">
          <input
            className="w-full py-2 px-4 border-2 border-blue-500 rounded-md"
            type="text"
            placeholder="Search"
            onChange={(e) => setSearch(e.target.value)}
          />
          {result.length > 0 && <div className="bg-gray-200 p-4 flex flex-col justify-center items-start w-full">
            
              {result.slice(0, 8).map((character) => (
                <div
                  key={character.item.name}
                  className="w-full m-1 flex flex-row gap-5 items-center"
                >
                  <img
                    className="w-16 aspect-square"
                    src={character.item.image}
                    alt={character.item.name}
                  />
                  <h2 className="text-2xl font-bold">{character.item.name}</h2>
                </div>
              ))}
          </div>}
        </div>

        {/*
          marriageCandidates.map((character) => (
            <div key={character.name} className="flex flex-col items-center">
              <img src={character.image} alt={character.name} />
              <h2 className="text-2xl font-bold">{character.name}</h2>
            </div>
          ))
          */}
      </div>
    </>
  );
};

export default Home;
